vendor: openai
models:
  - name: "gpt-4-0125-preview"
  - name: "gpt-4-turbo-preview"
  - name: "gpt-4-1106-preview"
  - name: "gpt-4-0613"
  - name: "gpt-4-32k-0613"
  - name: "gpt-3.5-turbo-0125"
  - name: "gpt-3.5-turbo-1106"